cmd_/home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.o := gcc -Wp,-MD,/home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/6/include  -I./arch/x86/include -I./arch/x86/include/generated/uapi -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -fno-pie -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-pie -no-pie -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -Wno-frame-address -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -DCC_HAVE_ASM_GOTO -Wall -Wstrict-prototypes -Wno-trigraphs -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -DENHANCED_STAT_DISPLAY -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=mt7603u -DRESOURCE_PRE_ALLOC -DCONFIG_RA_NAT_NONE -I/home/kev/WorkSpace/Project/MT7603U/include -DCAL_FREE_IC_SUPPORT -DUAPSD_SUPPORT -DMT_PS_CHECK -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DADHOC_WPA2PSK_SUPPORT -DWPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DSTATS_COUNT_SUPPORT -DCONFIG_CALIBRATION_COLLECTION -DMT7603 -DMT_BBP -DMT_RF -DRTMP_RF_RW_SUPPORT -DMT_MAC -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DMCS_LUT_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRTMP_EFUSE_SUPPORT -DCONFIG_ANDES_SUPPORT -DNEW_RATE_ADAPT_SUPPORT -DRTMP_WLAN_HOOK_SUPPORT -DCONFIG_FPGA_MODE -DRELEASE_EXCLUDE -DIP_ASSEMBLY -Wno-error=date-time  -DMODULE  -DKBUILD_BASENAME='"alg_ags"'  -DKBUILD_MODNAME='"mt7603u_sta"' -c -o /home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.o /home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.c

source_/home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.o := /home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.c

deps_/home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \
    $(wildcard include/config/ap/support.h) \

/home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.o: $(deps_/home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.o)

$(deps_/home/kev/WorkSpace/Project/MT7603U/os/linux/../../rate_ctrl/alg_ags.o):
