cmd_/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.o := gcc -Wp,-MD,/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/.rtusb_data.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.4.7/include  -I/usr/src/linux-headers-3.2.0-63-generic/arch/x86/include -Iarch/x86/include/generated -Iinclude  -include /usr/src/linux-headers-3.2.0-63-generic/include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -Wframe-larger-than=1024 -fno-omit-frame-pointer -fno-optimize-sibling-calls -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Wall -Wstrict-prototypes -Wno-trigraphs -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -DENHANCED_STAT_DISPLAY -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=mt7603u -DRESOURCE_PRE_ALLOC -DCONFIG_RA_NAT_NONE -I/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/include -DCAL_FREE_IC_SUPPORT -DUAPSD_SUPPORT -DMT_PS_CHECK -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DADHOC_WPA2PSK_SUPPORT -DWPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DSTATS_COUNT_SUPPORT -DCONFIG_CALIBRATION_COLLECTION -DMT7603 -DMT_BBP -DMT_RF -DRTMP_RF_RW_SUPPORT -DMT_MAC -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DMCS_LUT_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRTMP_EFUSE_SUPPORT -DCONFIG_ANDES_SUPPORT -DNEW_RATE_ADAPT_SUPPORT -DRTMP_WLAN_HOOK_SUPPORT -DCONFIG_FPGA_MODE -DRELEASE_EXCLUDE -DIP_ASSEMBLY  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rtusb_data)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7603u_sta)" -c -o /mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/.tmp_rtusb_data.o /mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.c

source_/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.o := /mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.c

deps_/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.o := \

/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.o: $(deps_/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.o)

$(deps_/mnt/hgfs/linux/MT7603U_DPA_LinuxSTA_3.0.0.4_20140825/DPA/os/linux/../../common/rtusb_data.o):
